name: Poll-api CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t polls-api:latest . --platform linux/amd64
      
    - name: Run container
      run: |
        docker run -d -p 5001:5001 --name polls-api-container polls-api:latest
        sleep 5
        curl http://localhost:5001/api/health || exit 1
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: | 
        pip install -r requirements.txt
    
    - name: Run test 
      run: |
        pytest -v
    
    - name: Stop docker and remove container
      if: always()
      run: |
        docker stop polls-api-container
        docker rm polls-api-container
    
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: Tag our docker image
      run: |
        docker tag polls-api:latest ${{secrets.DOCKERHUB_USERNAME}}/polls-api:latest
        docker tag polls-api:latest ${{secrets.DOCKERHUB_USERNAME}}/polls-api:${{ github.sha }}
    
    - name: Push to Docker hub
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/polls-api:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/polls-api:${{ github.sha }}
    
    - name: Trigger render reploy
      run: |
        curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}

